import { type NextPage } from "next";
import Head from "next/head";
import { useEffect, useRef } from "react";
import { useLocalStorage } from "../utils/useLocalState";
import dynamic from "next/dynamic";
import Link from "next/link";

type Note = {
  id: string;
  contents: string;
  createdAt: number;
};

const Options: NextPage = () => {
  const [apiKey, setApiKey] = useLocalStorage<string>("options.apiKey", "");

  return (
    <>
      <Head>
        <title>Motes - Options</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" flex min-h-screen flex-col items-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-4 px-4 py-16">
          <h1 className="mb-8 text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            <span className="text-[hsl(280,100%,70%)]">Options</span>
          </h1>
          <section className="flex w-full flex-col gap-4 rounded-xl bg-white/10 p-4 text-white focus-within:border">
            <h1 className="text-lg">Todoist Key</h1>
            <input
              aria-label="Todoist API Key"
              className="rounded-lg bg-transparent font-mono text-xl outline-none"
              value={apiKey}
              onChange={(e) => setApiKey(e.target.value)}
            ></input>
            <p className="right-4 text-sm text-white/50">
              Used to sync notes with Todoist. You can find your API Key in
              Settings → Integrations → Developer. Your key is stored locally on
              this device.
            </p>
          </section>
          <section className="w-full">
            <Link
              href="/"
              className="flex w-max flex-col rounded-md bg-white/10 p-4 px-8
                text-white focus-within:border"
            >
              Back
            </Link>
          </section>
        </div>
      </main>
    </>
  );
};
export default Options;
